version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=your-secret-key-change-this-in-production
      - NEXTAUTH_URL=http://localhost:3000
      - SMTP_HOST=smtp.ethereal.email
      - SMTP_PORT=587
      - SMTP_USER=your-email@ethereal.email
      - SMTP_PASS=your-password
      - EMAIL_FROM=noreply@utente-cliente.com
    volumes:
      - ./prisma:/app/prisma
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
